plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  Exclude:
    - 'lib/zitadel-client/models/**/*'
    - 'lib/zitadel-client/api/**/*'
    - 'vendor/**/*'
  NewCops: enable
  TargetRubyVersion: 2.7

Layout/LineLength:
  Max: 130

Style/StringLiterals:
  EnforcedStyle: single_quotes

Metrics/AbcSize:
  Exclude:
    - 'test/**/*'

Metrics/BlockLength:
  Max: 100
  Exclude:
    - 'spec/**/*'
