# frozen_string_literal: true

# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you
# in integrating with your Zitadel environment. This SDK enables you to handle
# resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

require_relative 'lib/zitadel/client/version'

Gem::Specification.new do |s|
  s.name        = 'zitadel-client'
  s.version     = Zitadel::Client::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ['OpenAPI-Generator']
  s.summary     = 'Zitadel SDK Ruby Gem'
  s.description = 'The Zitadel SDK is a convenience wrapper around the Zitadel ' \
                  'APIs to assist you in integrating with your Zitadel ' \
                  'environment. This SDK enables you to handle resources, ' \
                  'settings, and configurations within the Zitadel platform.'
  s.license     = 'MIT'
  s.required_ruby_version = '>= 3.4'
  s.metadata['rubygems_mfa_required'] = 'true'

  s.add_dependency 'dry-struct', '~> 1.6'
  s.add_dependency 'dry-types', '~> 1.7'
  s.add_dependency 'faraday', '~> 2.0'
  s.add_dependency 'faraday-follow_redirects', '~> 0.3'
  # 4.8: format: duration — ISO-8601 duration parsing/formatting (no
  # stdlib equivalent; lighter than ActiveSupport::Duration).
  s.add_dependency 'iso8601', '~> 0.13'
  # 4.8: format: time — time-of-day (HH:MM:SS) values; Ruby has no
  # native time-of-day type so we standardise on Tod::TimeOfDay.
  s.add_dependency 'tod', '~> 3.1'
  # JWT signing for the private-key (JWT bearer) authenticator.
  s.add_dependency 'jwt', '~> 3.0'
  # Hand-written entrypoint: Zeitwerk autoloading + redefinition-warning
  # suppression for the constant-tree wiring.
  s.add_dependency 'warning', '~> 1.5'
  s.add_dependency 'zeitwerk', '~> 2.5'

  s.files = Dir['lib/**/*', 'sig/**/*', 'README.md', 'Gemfile', 'zitadel-client.gemspec']
  s.require_paths = ['lib']
end
