=begin
# API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for ZitadelClient::IdentityProviderServiceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'IdentityProviderServiceApi' do
  before do
    # run before each test
    @api_instance = ZitadelClient::IdentityProviderServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of IdentityProviderServiceApi' do
    it 'should create an instance of IdentityProviderServiceApi' do
      expect(@api_instance).to be_instance_of(ZitadelClient::IdentityProviderServiceApi)
    end
  end

  # unit tests for get_idpby_id
  # Get identity provider (IdP) by ID
  # Returns an identity provider (social/enterprise login) by its ID, which can be of the type Google, AzureAD, etc.
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [V2GetIDPByIDResponse]
  describe 'get_idpby_id test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
