=begin
# API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ZitadelClient::UserServiceAddIDPLinkBody
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ZitadelClient::UserServiceAddIDPLinkBody do
  let(:instance) { ZitadelClient::UserServiceAddIDPLinkBody.new }

  describe 'test an instance of UserServiceAddIDPLinkBody' do
    it 'should create an instance of UserServiceAddIDPLinkBody' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(ZitadelClient::UserServiceAddIDPLinkBody)
    end
  end

  describe 'test attribute "idp_link"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
