=begin
# API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ZitadelClient::V2Challenges
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ZitadelClient::V2Challenges do
  let(:instance) { ZitadelClient::V2Challenges.new }

  describe 'test an instance of V2Challenges' do
    it 'should create an instance of V2Challenges' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(ZitadelClient::V2Challenges)
    end
  end

  describe 'test attribute "web_auth_n"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "otp_sms"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "otp_email"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
