=begin
#merged spec

#merged spec

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ZitadelClient::V2ListIDPLinksResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ZitadelClient::V2ListIDPLinksResponse do
  let(:instance) { ZitadelClient::V2ListIDPLinksResponse.new }

  describe 'test an instance of V2ListIDPLinksResponse' do
    it 'should create an instance of V2ListIDPLinksResponse' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(ZitadelClient::V2ListIDPLinksResponse)
    end
  end

  describe 'test attribute "details"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "result"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
