=begin
# API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for ZitadelClient::V2SAMLBinding
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe ZitadelClient::V2SAMLBinding do
  let(:instance) { ZitadelClient::V2SAMLBinding.new }

  describe 'test an instance of V2SAMLBinding' do
    it 'should create an instance of V2SAMLBinding' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(ZitadelClient::V2SAMLBinding)
    end
  end

end
