# frozen_string_literal: true

# rubocop:disable all
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

require 'date'
require 'iso8601'
require 'time'
require 'tod'
require 'dry-struct'

# :nodoc:
module Types
  # The dry-types module built dynamically by +Dry.Types()+. Bound to a
  # constant first so YARD resolves the mixin statically (it cannot resolve
  # the bare +include Dry.Types()+ method-call form and would otherwise emit
  # an "Undocumentable mixin" warning).
  Builder = Dry.Types()
  include Builder

  Required = Types::Any.constructor do |v|
    raise Dry::Types::CoercionError, 'value cannot be nil' if v.nil?

    v
  end
end

# :nodoc:
module Zitadel::Client
  # Model classes generated from OpenAPI schemas.
  module Models
    # Model class for ActionServiceListExecutionsRequest.
    class ActionServiceListExecutionsRequest < Dry::Struct
      # Attribute mapping from ruby-style variable name to JSON key.
      ATTRIBUTE_MAP = {
        pagination: 'pagination',
        sorting_column: 'sortingColumn',
        filters: 'filters'
      }.freeze

      # Inverse mapping from JSON key to ruby attribute name.
      JSON_KEY_MAP = ATTRIBUTE_MAP.invert.freeze

      # Attribute type mapping.
      OPENAPI_TYPES = {
        pagination: 'ActionServicePaginationRequest',
        sorting_column: 'ActionServiceExecutionFieldName',
        filters: 'Array<ActionServiceExecutionSearchFilter>'
      }.freeze

      # Per-attribute OpenAPI `format` for properties whose wire form
      # differs from their Ruby surface (`byte` → base64-decoded binary
      # String, `uuid` → RFC 4122 validated String). The `byte[]` /
      # `uuid[]` variants apply the same transform to every item of an
      # array-typed property. Consumed by Zitadel::Client::ObjectSerializer
      # on the (de)serialize path.
      # @type var openapi_formats: Hash[Symbol, String]
      openapi_formats = {
        
      }
      OPENAPI_FORMATS = openapi_formats.freeze

      # Transform incoming hash keys from JSON format to Ruby attribute names.
      transform_keys do |key|
        JSON_KEY_MAP[key.to_s] || key.to_sym
      end

      # @example null
      attribute :pagination, Types::Any.optional.meta(omittable: true)
      # @example null
      attribute :sorting_column, Types::Any.optional.meta(omittable: true)
      # Define the criteria to query for.
      # @example null
      attribute :filters, Types::Any.optional.meta(omittable: true)
    end
  end
end
