# frozen_string_literal: true

# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

require 'date'
require 'iso8601'
require 'time'
require 'tod'
require 'dry-struct'
require_relative '../types'

# :nodoc:
module Zitadel::Client
  # Model classes generated from OpenAPI schemas.
  module Models
    # Enumeration of allowed values for BetaSettingsServiceSecondFactorType.
    class BetaSettingsServiceSecondFactorType
      SECOND_FACTOR_TYPE_UNSPECIFIED = 'SECOND_FACTOR_TYPE_UNSPECIFIED'
      SECOND_FACTOR_TYPE_OTP = 'SECOND_FACTOR_TYPE_OTP'
      SECOND_FACTOR_TYPE_U2_F = 'SECOND_FACTOR_TYPE_U2F'
      SECOND_FACTOR_TYPE_OTP_EMAIL = 'SECOND_FACTOR_TYPE_OTP_EMAIL'
      SECOND_FACTOR_TYPE_OTP_SMS = 'SECOND_FACTOR_TYPE_OTP_SMS'

      # Frozen set of all allowed values, used for validation.
      VALUES = [SECOND_FACTOR_TYPE_UNSPECIFIED, SECOND_FACTOR_TYPE_OTP, SECOND_FACTOR_TYPE_U2_F, SECOND_FACTOR_TYPE_OTP_EMAIL, SECOND_FACTOR_TYPE_OTP_SMS].freeze

      def self.all_vars
        VALUES
      end

      # Validate that +value+ is a recognized enum value.
      #
      # @param value [Object] the value to validate
      # @return [Object] the value, if valid
      # @raise [ArgumentError] if +value+ is not in {VALUES}
      def self.validate!(value)
        return value if value.nil? || VALUES.include?(value)

        raise ArgumentError, "Unknown enum value for BetaSettingsServiceSecondFactorType: #{value.inspect} (allowed: #{VALUES.inspect})"
      end
    end
  end
end
