# frozen_string_literal: true

# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

require 'date'
require 'iso8601'
require 'time'
require 'tod'
require 'dry-struct'
require_relative '../types'

# :nodoc:
module Zitadel::Client
  # Model classes generated from OpenAPI schemas.
  module Models
    # Enumeration of allowed values for BetaWebKeyServiceState.
    class BetaWebKeyServiceState
      STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
      STATE_INITIAL = 'STATE_INITIAL'
      STATE_ACTIVE = 'STATE_ACTIVE'
      STATE_INACTIVE = 'STATE_INACTIVE'
      STATE_REMOVED = 'STATE_REMOVED'

      # Frozen set of all allowed values, used for validation.
      VALUES = [STATE_UNSPECIFIED, STATE_INITIAL, STATE_ACTIVE, STATE_INACTIVE, STATE_REMOVED].freeze

      def self.all_vars
        VALUES
      end

      # Validate that +value+ is a recognized enum value.
      #
      # @param value [Object] the value to validate
      # @return [Object] the value, if valid
      # @raise [ArgumentError] if +value+ is not in {VALUES}
      def self.validate!(value)
        return value if value.nil? || VALUES.include?(value)

        raise ArgumentError, "Unknown enum value for BetaWebKeyServiceState: #{value.inspect} (allowed: #{VALUES.inspect})"
      end
    end
  end
end
