# frozen_string_literal: true

# rubocop:disable all
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

require 'date'
require 'iso8601'
require 'time'
require 'tod'
require 'dry-struct'

# :nodoc:
module Types
  # The dry-types module built dynamically by +Dry.Types()+. Bound to a
  # constant first so YARD resolves the mixin statically (it cannot resolve
  # the bare +include Dry.Types()+ method-call form and would otherwise emit
  # an "Undocumentable mixin" warning).
  Builder = Dry.Types()
  include Builder

  Required = Types::Any.constructor do |v|
    raise Dry::Types::CoercionError, 'value cannot be nil' if v.nil?

    v
  end
end

# :nodoc:
module Zitadel::Client
  # Model classes generated from OpenAPI schemas.
  module Models
    # Model class for BetaUserServiceRegisterPasskeyResponse.
    class BetaUserServiceRegisterPasskeyResponse < Dry::Struct
      # Attribute mapping from ruby-style variable name to JSON key.
      ATTRIBUTE_MAP = {
        details: 'details',
        passkey_id: 'passkeyId',
        public_key_credential_creation_options: 'publicKeyCredentialCreationOptions'
      }.freeze

      # Inverse mapping from JSON key to ruby attribute name.
      JSON_KEY_MAP = ATTRIBUTE_MAP.invert.freeze

      # Attribute type mapping.
      OPENAPI_TYPES = {
        details: 'BetaUserServiceDetails',
        passkey_id: 'String',
        public_key_credential_creation_options: 'Hash<String, Object>'
      }.freeze

      # Per-attribute OpenAPI `format` for properties whose wire form
      # differs from their Ruby surface (`byte` → base64-decoded binary
      # String, `uuid` → RFC 4122 validated String). The `byte[]` /
      # `uuid[]` variants apply the same transform to every item of an
      # array-typed property. Consumed by ::Zitadel::Client::ObjectSerializer
      # on the (de)serialize path.
      # @type var openapi_formats: Hash[Symbol, String]
      openapi_formats = {
        
      }
      OPENAPI_FORMATS = openapi_formats.freeze

      # Transform incoming hash keys from JSON format to Ruby attribute names.
      transform_keys do |key|
        JSON_KEY_MAP[key.to_s] || key.to_sym
      end

      # @example null
      attribute :details, Types::Any.optional.meta(omittable: true)
      # @example null
      attribute :passkey_id, Types::Any.optional.meta(omittable: true)
      # `Struct` represents a structured data value, consisting of fields  which map to dynamically typed values. In some languages, `Struct`  might be supported by a native representation. For example, in  scripting languages like JS a struct is represented as an  object. The details of that representation are described together  with the proto support for the language.   The JSON representation for `Struct` is JSON object.
      # @example null
      attribute :public_key_credential_creation_options, Types::Any.optional.meta(omittable: true)
    end
  end
end
