# frozen_string_literal: true

# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

require 'date'
require 'iso8601'
require 'time'
require 'tod'
require 'dry-struct'
require_relative '../types'

# :nodoc:
module Zitadel::Client
  # Model classes generated from OpenAPI schemas.
  module Models
    # Enumeration of allowed values for BetaAppServiceApplicationKeysSorting.
    class BetaAppServiceApplicationKeysSorting
      APPLICATION_KEYS_SORT_BY_ID = 'APPLICATION_KEYS_SORT_BY_ID'
      APPLICATION_KEYS_SORT_BY_PROJECT_ID = 'APPLICATION_KEYS_SORT_BY_PROJECT_ID'
      APPLICATION_KEYS_SORT_BY_APPLICATION_ID = 'APPLICATION_KEYS_SORT_BY_APPLICATION_ID'
      APPLICATION_KEYS_SORT_BY_CREATION_DATE = 'APPLICATION_KEYS_SORT_BY_CREATION_DATE'
      APPLICATION_KEYS_SORT_BY_ORGANIZATION_ID = 'APPLICATION_KEYS_SORT_BY_ORGANIZATION_ID'
      APPLICATION_KEYS_SORT_BY_EXPIRATION = 'APPLICATION_KEYS_SORT_BY_EXPIRATION'
      APPLICATION_KEYS_SORT_BY_TYPE = 'APPLICATION_KEYS_SORT_BY_TYPE'

      # Frozen set of all allowed values, used for validation.
      VALUES = [APPLICATION_KEYS_SORT_BY_ID, APPLICATION_KEYS_SORT_BY_PROJECT_ID, APPLICATION_KEYS_SORT_BY_APPLICATION_ID, APPLICATION_KEYS_SORT_BY_CREATION_DATE, APPLICATION_KEYS_SORT_BY_ORGANIZATION_ID, APPLICATION_KEYS_SORT_BY_EXPIRATION, APPLICATION_KEYS_SORT_BY_TYPE].freeze

      def self.all_vars
        VALUES
      end

      # Validate that +value+ is a recognized enum value.
      #
      # @param value [Object] the value to validate
      # @return [Object] the value, if valid
      # @raise [ArgumentError] if +value+ is not in {VALUES}
      def self.validate!(value)
        return value if value.nil? || VALUES.include?(value)

        raise ArgumentError, "Unknown enum value for BetaAppServiceApplicationKeysSorting: #{value.inspect} (allowed: #{VALUES.inspect})"
      end
    end
  end
end
