=begin
#Zitadel SDK

#The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.14.0

=end

require 'date'
require 'time'

module Zitadel::Client::Models
          class IdentityProviderServiceSAMLSignatureAlgorithm
    SAML_SIGNATURE_UNSPECIFIED = "SAML_SIGNATURE_UNSPECIFIED".freeze
    SAML_SIGNATURE_RSA_SHA1 = "SAML_SIGNATURE_RSA_SHA1".freeze
    SAML_SIGNATURE_RSA_SHA256 = "SAML_SIGNATURE_RSA_SHA256".freeze
    SAML_SIGNATURE_RSA_SHA512 = "SAML_SIGNATURE_RSA_SHA512".freeze

    def self.all_vars
      @all_vars ||= [SAML_SIGNATURE_UNSPECIFIED, SAML_SIGNATURE_RSA_SHA1, SAML_SIGNATURE_RSA_SHA256, SAML_SIGNATURE_RSA_SHA512].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if IdentityProviderServiceSAMLSignatureAlgorithm.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #Zitadel::Client::Models::IdentityProviderServiceSAMLSignatureAlgorithm"
    end
  end

end
