# frozen_string_literal: true

# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

require 'date'
require 'iso8601'
require 'time'
require 'tod'
require 'dry-struct'
require_relative '../types'

# :nodoc:
module Zitadel::Client
  # Model classes generated from OpenAPI schemas.
  module Models
    # Enumeration of allowed values for IdentityProviderServiceSAMLNameIDFormat.
    class IdentityProviderServiceSAMLNameIDFormat
      SAML_NAME_ID_FORMAT_UNSPECIFIED = 'SAML_NAME_ID_FORMAT_UNSPECIFIED'
      SAML_NAME_ID_FORMAT_EMAIL_ADDRESS = 'SAML_NAME_ID_FORMAT_EMAIL_ADDRESS'
      SAML_NAME_ID_FORMAT_PERSISTENT = 'SAML_NAME_ID_FORMAT_PERSISTENT'
      SAML_NAME_ID_FORMAT_TRANSIENT = 'SAML_NAME_ID_FORMAT_TRANSIENT'

      # Frozen set of all allowed values, used for validation.
      VALUES = [SAML_NAME_ID_FORMAT_UNSPECIFIED, SAML_NAME_ID_FORMAT_EMAIL_ADDRESS, SAML_NAME_ID_FORMAT_PERSISTENT, SAML_NAME_ID_FORMAT_TRANSIENT].freeze

      def self.all_vars
        VALUES
      end

      # Validate that +value+ is a recognized enum value.
      #
      # @param value [Object] the value to validate
      # @return [Object] the value, if valid
      # @raise [ArgumentError] if +value+ is not in {VALUES}
      def self.validate!(value)
        return value if value.nil? || VALUES.include?(value)

        raise ArgumentError, "Unknown enum value for IdentityProviderServiceSAMLNameIDFormat: #{value.inspect} (allowed: #{VALUES.inspect})"
      end
    end
  end
end
