# frozen_string_literal: true

# rubocop:disable all
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

require 'date'
require 'iso8601'
require 'time'
require 'tod'
require 'dry-struct'

# :nodoc:
module Types
  # The dry-types module built dynamically by +Dry.Types()+. Bound to a
  # constant first so YARD resolves the mixin statically (it cannot resolve
  # the bare +include Dry.Types()+ method-call form and would otherwise emit
  # an "Undocumentable mixin" warning).
  Builder = Dry.Types()
  include Builder

  Required = Types::Any.constructor do |v|
    raise Dry::Types::CoercionError, 'value cannot be nil' if v.nil?

    v
  end
end

# :nodoc:
module Zitadel::Client
  # Model classes generated from OpenAPI schemas.
  module Models
    # Model class for ProjectServiceCreateProjectRequest.
    class ProjectServiceCreateProjectRequest < Dry::Struct
      # Attribute mapping from ruby-style variable name to JSON key.
      ATTRIBUTE_MAP = {
        organization_id: 'organizationId',
        project_id: 'projectId',
        name: 'name',
        project_role_assertion: 'projectRoleAssertion',
        authorization_required: 'authorizationRequired',
        project_access_required: 'projectAccessRequired',
        private_labeling_setting: 'privateLabelingSetting'
      }.freeze

      # Inverse mapping from JSON key to ruby attribute name.
      JSON_KEY_MAP = ATTRIBUTE_MAP.invert.freeze

      # Attribute type mapping.
      OPENAPI_TYPES = {
        organization_id: 'String',
        project_id: 'String',
        name: 'String',
        project_role_assertion: 'Boolean',
        authorization_required: 'Boolean',
        project_access_required: 'Boolean',
        private_labeling_setting: 'ProjectServicePrivateLabelingSetting'
      }.freeze

      # Per-attribute OpenAPI `format` for properties whose wire form
      # differs from their Ruby surface (`byte` → base64-decoded binary
      # String, `uuid` → RFC 4122 validated String). The `byte[]` /
      # `uuid[]` variants apply the same transform to every item of an
      # array-typed property. Consumed by ::Zitadel::Client::ObjectSerializer
      # on the (de)serialize path.
      # @type var openapi_formats: Hash[Symbol, String]
      openapi_formats = {
        
      }
      OPENAPI_FORMATS = openapi_formats.freeze

      # Transform incoming hash keys from JSON format to Ruby attribute names.
      transform_keys do |key|
        JSON_KEY_MAP[key.to_s] || key.to_sym
      end

      # OrganizationID is the unique identifier of the organization the project belongs to.
      # @example null
      attribute :organization_id, Types::Any.optional.meta(omittable: true)
      # ProjectID is the unique identifier of the new project. This field is optional.  If omitted, the system will generate a unique ID for you. This is the  recommended way. The generated ID will be returned in the response.
      # @example null
      attribute :project_id, Types::Any.optional.meta(omittable: true)
      # Name of the project. This might be presented to users, e.g. in sign-in flows.
      # @example null
      attribute :name, Types::Any.optional.meta(omittable: true)
      # ProjectRoleAssertion is a  setting that can be enabled to have role information  included in the user info endpoint.  It is also dependent on your application settings to include it in tokens and other types.
      # @example null
      attribute :project_role_assertion, Types::Any.optional.meta(omittable: true)
      # AuthorizationRequired is a boolean flag that can be enabled to check if a user has  an authorization to use this project assigned when login into an application of this project.
      # @example null
      attribute :authorization_required, Types::Any.optional.meta(omittable: true)
      # ProjectAccessRequired is a boolean flag that can be enabled to check if the organization  of the user, that is trying to log in,  has access to this project (either owns the project or is granted).
      # @example null
      attribute :project_access_required, Types::Any.optional.meta(omittable: true)
      # @example null
      attribute :private_labeling_setting, Types::Any.optional.meta(omittable: true)
    end
  end
end
