=begin
#Zitadel SDK

#The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.13.0

=end

require 'date'
require 'time'

module Zitadel::Client::Models
          class UserServiceKeyFieldName
    KEY_FIELD_NAME_UNSPECIFIED = "KEY_FIELD_NAME_UNSPECIFIED".freeze
    KEY_FIELD_NAME_CREATED_DATE = "KEY_FIELD_NAME_CREATED_DATE".freeze
    KEY_FIELD_NAME_ID = "KEY_FIELD_NAME_ID".freeze
    KEY_FIELD_NAME_USER_ID = "KEY_FIELD_NAME_USER_ID".freeze
    KEY_FIELD_NAME_ORGANIZATION_ID = "KEY_FIELD_NAME_ORGANIZATION_ID".freeze
    KEY_FIELD_NAME_KEY_EXPIRATION_DATE = "KEY_FIELD_NAME_KEY_EXPIRATION_DATE".freeze

    def self.all_vars
      @all_vars ||= [KEY_FIELD_NAME_UNSPECIFIED, KEY_FIELD_NAME_CREATED_DATE, KEY_FIELD_NAME_ID, KEY_FIELD_NAME_USER_ID, KEY_FIELD_NAME_ORGANIZATION_ID, KEY_FIELD_NAME_KEY_EXPIRATION_DATE].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if UserServiceKeyFieldName.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #Zitadel::Client::Models::UserServiceKeyFieldName"
    end
  end

end
