# frozen_string_literal: true

# rubocop:disable all
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

require 'date'
require 'iso8601'
require 'time'
require 'tod'
require 'dry-struct'

# :nodoc:
module Types
  # The dry-types module built dynamically by +Dry.Types()+. Bound to a
  # constant first so YARD resolves the mixin statically (it cannot resolve
  # the bare +include Dry.Types()+ method-call form and would otherwise emit
  # an "Undocumentable mixin" warning).
  Builder = Dry.Types()
  include Builder

  Required = Types::Any.constructor do |v|
    raise Dry::Types::CoercionError, 'value cannot be nil' if v.nil?

    v
  end
end

# :nodoc:
module Zitadel::Client
  # Model classes generated from OpenAPI schemas.
  module Models
    # Model class for UserServiceSearchQuery.
    class UserServiceSearchQuery < Dry::Struct
      # Attribute mapping from ruby-style variable name to JSON key.
      ATTRIBUTE_MAP = {
        and_query: 'andQuery',
        display_name_query: 'displayNameQuery',
        email_query: 'emailQuery',
        first_name_query: 'firstNameQuery',
        in_user_emails_query: 'inUserEmailsQuery',
        in_user_ids_query: 'inUserIdsQuery',
        last_name_query: 'lastNameQuery',
        login_name_query: 'loginNameQuery',
        metadata_key_filter: 'metadataKeyFilter',
        metadata_value_filter: 'metadataValueFilter',
        nick_name_query: 'nickNameQuery',
        not_query: 'notQuery',
        or_query: 'orQuery',
        organization_id_query: 'organizationIdQuery',
        phone_query: 'phoneQuery',
        state_query: 'stateQuery',
        type_query: 'typeQuery',
        user_name_query: 'userNameQuery'
      }.freeze

      # Inverse mapping from JSON key to ruby attribute name.
      JSON_KEY_MAP = ATTRIBUTE_MAP.invert.freeze

      # Attribute type mapping.
      OPENAPI_TYPES = {
        and_query: 'UserServiceAndQuery',
        display_name_query: 'UserServiceDisplayNameQuery',
        email_query: 'UserServiceEmailQuery',
        first_name_query: 'UserServiceFirstNameQuery',
        in_user_emails_query: 'UserServiceInUserEmailsQuery',
        in_user_ids_query: 'UserServiceInUserIDQuery',
        last_name_query: 'UserServiceLastNameQuery',
        login_name_query: 'UserServiceLoginNameQuery',
        metadata_key_filter: 'UserServiceMetadataKeyFilter',
        metadata_value_filter: 'UserServiceMetadataValueFilter',
        nick_name_query: 'UserServiceNickNameQuery',
        not_query: 'UserServiceNotQuery',
        or_query: 'UserServiceOrQuery',
        organization_id_query: 'UserServiceOrganizationIdQuery',
        phone_query: 'UserServicePhoneQuery',
        state_query: 'UserServiceStateQuery',
        type_query: 'UserServiceTypeQuery',
        user_name_query: 'UserServiceUserNameQuery'
      }.freeze

      # Per-attribute OpenAPI `format` for properties whose wire form
      # differs from their Ruby surface (`byte` → base64-decoded binary
      # String, `uuid` → RFC 4122 validated String). The `byte[]` /
      # `uuid[]` variants apply the same transform to every item of an
      # array-typed property. Consumed by Zitadel::Client::ObjectSerializer
      # on the (de)serialize path.
      # @type var openapi_formats: Hash[Symbol, String]
      openapi_formats = {
        
      }
      OPENAPI_FORMATS = openapi_formats.freeze

      # Transform incoming hash keys from JSON format to Ruby attribute names.
      transform_keys do |key|
        JSON_KEY_MAP[key.to_s] || key.to_sym
      end

      # @example null
      attribute :and_query, Types::Any.optional.meta(omittable: true)
      # @example null
      attribute :display_name_query, Types::Any.optional.meta(omittable: true)
      # @example null
      attribute :email_query, Types::Any.optional.meta(omittable: true)
      # @example null
      attribute :first_name_query, Types::Any.optional.meta(omittable: true)
      # @example null
      attribute :in_user_emails_query, Types::Any.optional.meta(omittable: true)
      # @example null
      attribute :in_user_ids_query, Types::Any.optional.meta(omittable: true)
      # @example null
      attribute :last_name_query, Types::Any.optional.meta(omittable: true)
      # @example null
      attribute :login_name_query, Types::Any.optional.meta(omittable: true)
      # @example null
      attribute :metadata_key_filter, Types::Any.optional.meta(omittable: true)
      # @example null
      attribute :metadata_value_filter, Types::Any.optional.meta(omittable: true)
      # @example null
      attribute :nick_name_query, Types::Any.optional.meta(omittable: true)
      # @example null
      attribute :not_query, Types::Any.optional.meta(omittable: true)
      # @example null
      attribute :or_query, Types::Any.optional.meta(omittable: true)
      # @example null
      attribute :organization_id_query, Types::Any.optional.meta(omittable: true)
      # @example null
      attribute :phone_query, Types::Any.optional.meta(omittable: true)
      # @example null
      attribute :state_query, Types::Any.optional.meta(omittable: true)
      # @example null
      attribute :type_query, Types::Any.optional.meta(omittable: true)
      # @example null
      attribute :user_name_query, Types::Any.optional.meta(omittable: true)
    end
  end
end
