class ClientCredentialsAuthenticator

  def initialize: (OpenId, String, String, Set[String]) -> void

  def get_grant: (OAuth2::Client, String) -> OAuth2::AccessToken

  def self.builder: (String, String, String) -> ClientCredentialsAuthenticatorBuilder

  class ClientCredentialsAuthenticatorBuilder
    @client_id: String
    @client_secret: String

    def initialize: (String, String, String) -> void

    def build: -> ClientCredentialsAuthenticator
  end

end
