class OAuthAuthenticatorBuilder
  @auth_scopes: Set[String]
  @open_id: OpenId

  attr_reader open_id: OpenId
  attr_reader auth_scopes: Set[String]

  def initialize: (String) -> void

  def auth_scopes: -> untyped

  def scopes: -> untyped
end
