class OpenId
  @host_endpoint: String
  @token_endpoint: String

  def initialize: (String) -> void

  def self.build_well_known_url: (String) -> String

  def get_host_endpoint: -> String

  def get_token_endpoint: -> String
end
