module Zitadel::Client
  module Api
    class BetaOrganizationServiceApi < BaseApi
      def initialize: (?::Zitadel::Client::ApiClient? api_client, ?::Zitadel::Client::Configuration config, ?::Zitadel::Client::Auth::Authenticator? authenticator) -> void
      def activate_organization: (Models::BetaOrganizationServiceActivateOrganizationRequest beta_organization_service_activate_organization_request) -> Models::BetaOrganizationServiceActivateOrganizationResponse
      def activate_organization_with_http_info: (Models::BetaOrganizationServiceActivateOrganizationRequest beta_organization_service_activate_organization_request) -> ::Zitadel::Client::ApiResult[Models::BetaOrganizationServiceActivateOrganizationResponse]
      def add_organization_domain: (Models::BetaOrganizationServiceAddOrganizationDomainRequest beta_organization_service_add_organization_domain_request) -> Models::BetaOrganizationServiceAddOrganizationDomainResponse
      def add_organization_domain_with_http_info: (Models::BetaOrganizationServiceAddOrganizationDomainRequest beta_organization_service_add_organization_domain_request) -> ::Zitadel::Client::ApiResult[Models::BetaOrganizationServiceAddOrganizationDomainResponse]
      def create_organization: (Models::BetaOrganizationServiceCreateOrganizationRequest beta_organization_service_create_organization_request) -> Models::BetaOrganizationServiceCreateOrganizationResponse
      def create_organization_with_http_info: (Models::BetaOrganizationServiceCreateOrganizationRequest beta_organization_service_create_organization_request) -> ::Zitadel::Client::ApiResult[Models::BetaOrganizationServiceCreateOrganizationResponse]
      def deactivate_organization: (Models::BetaOrganizationServiceDeactivateOrganizationRequest beta_organization_service_deactivate_organization_request) -> Models::BetaOrganizationServiceDeactivateOrganizationResponse
      def deactivate_organization_with_http_info: (Models::BetaOrganizationServiceDeactivateOrganizationRequest beta_organization_service_deactivate_organization_request) -> ::Zitadel::Client::ApiResult[Models::BetaOrganizationServiceDeactivateOrganizationResponse]
      def delete_organization: (Models::BetaOrganizationServiceDeleteOrganizationRequest beta_organization_service_delete_organization_request) -> Models::BetaOrganizationServiceDeleteOrganizationResponse
      def delete_organization_with_http_info: (Models::BetaOrganizationServiceDeleteOrganizationRequest beta_organization_service_delete_organization_request) -> ::Zitadel::Client::ApiResult[Models::BetaOrganizationServiceDeleteOrganizationResponse]
      def delete_organization_domain: (Models::BetaOrganizationServiceDeleteOrganizationDomainRequest beta_organization_service_delete_organization_domain_request) -> Models::BetaOrganizationServiceDeleteOrganizationDomainResponse
      def delete_organization_domain_with_http_info: (Models::BetaOrganizationServiceDeleteOrganizationDomainRequest beta_organization_service_delete_organization_domain_request) -> ::Zitadel::Client::ApiResult[Models::BetaOrganizationServiceDeleteOrganizationDomainResponse]
      def delete_organization_metadata: (Models::BetaOrganizationServiceDeleteOrganizationMetadataRequest beta_organization_service_delete_organization_metadata_request) -> Models::BetaOrganizationServiceDeleteOrganizationMetadataResponse
      def delete_organization_metadata_with_http_info: (Models::BetaOrganizationServiceDeleteOrganizationMetadataRequest beta_organization_service_delete_organization_metadata_request) -> ::Zitadel::Client::ApiResult[Models::BetaOrganizationServiceDeleteOrganizationMetadataResponse]
      def generate_organization_domain_validation: (Models::BetaOrganizationServiceGenerateOrganizationDomainValidationRequest beta_organization_service_generate_organization_domain_validation_request) -> Models::BetaOrganizationServiceGenerateOrganizationDomainValidationResponse
      def generate_organization_domain_validation_with_http_info: (Models::BetaOrganizationServiceGenerateOrganizationDomainValidationRequest beta_organization_service_generate_organization_domain_validation_request) -> ::Zitadel::Client::ApiResult[Models::BetaOrganizationServiceGenerateOrganizationDomainValidationResponse]
      def list_organization_domains: (Models::BetaOrganizationServiceListOrganizationDomainsRequest beta_organization_service_list_organization_domains_request) -> Models::BetaOrganizationServiceListOrganizationDomainsResponse
      def list_organization_domains_with_http_info: (Models::BetaOrganizationServiceListOrganizationDomainsRequest beta_organization_service_list_organization_domains_request) -> ::Zitadel::Client::ApiResult[Models::BetaOrganizationServiceListOrganizationDomainsResponse]
      def list_organization_metadata: (Models::BetaOrganizationServiceListOrganizationMetadataRequest beta_organization_service_list_organization_metadata_request) -> Models::BetaOrganizationServiceListOrganizationMetadataResponse
      def list_organization_metadata_with_http_info: (Models::BetaOrganizationServiceListOrganizationMetadataRequest beta_organization_service_list_organization_metadata_request) -> ::Zitadel::Client::ApiResult[Models::BetaOrganizationServiceListOrganizationMetadataResponse]
      def list_organizations: (Models::BetaOrganizationServiceListOrganizationsRequest beta_organization_service_list_organizations_request) -> Models::BetaOrganizationServiceListOrganizationsResponse
      def list_organizations_with_http_info: (Models::BetaOrganizationServiceListOrganizationsRequest beta_organization_service_list_organizations_request) -> ::Zitadel::Client::ApiResult[Models::BetaOrganizationServiceListOrganizationsResponse]
      def set_organization_metadata: (Models::BetaOrganizationServiceSetOrganizationMetadataRequest beta_organization_service_set_organization_metadata_request) -> Models::BetaOrganizationServiceSetOrganizationMetadataResponse
      def set_organization_metadata_with_http_info: (Models::BetaOrganizationServiceSetOrganizationMetadataRequest beta_organization_service_set_organization_metadata_request) -> ::Zitadel::Client::ApiResult[Models::BetaOrganizationServiceSetOrganizationMetadataResponse]
      def update_organization: (Models::BetaOrganizationServiceUpdateOrganizationRequest beta_organization_service_update_organization_request) -> Models::BetaOrganizationServiceUpdateOrganizationResponse
      def update_organization_with_http_info: (Models::BetaOrganizationServiceUpdateOrganizationRequest beta_organization_service_update_organization_request) -> ::Zitadel::Client::ApiResult[Models::BetaOrganizationServiceUpdateOrganizationResponse]
      def verify_organization_domain: (Models::BetaOrganizationServiceVerifyOrganizationDomainRequest beta_organization_service_verify_organization_domain_request) -> Models::BetaOrganizationServiceVerifyOrganizationDomainResponse
      def verify_organization_domain_with_http_info: (Models::BetaOrganizationServiceVerifyOrganizationDomainRequest beta_organization_service_verify_organization_domain_request) -> ::Zitadel::Client::ApiResult[Models::BetaOrganizationServiceVerifyOrganizationDomainResponse]
    end
  end
end
