module Zitadel::Client
  module Api
    class BetaSettingsServiceApi < BaseApi
      def initialize: (?::Zitadel::Client::ApiClient? api_client, ?::Zitadel::Client::Configuration config, ?::Zitadel::Client::Auth::Authenticator? authenticator) -> void
      def get_active_identity_providers: (Models::BetaSettingsServiceGetActiveIdentityProvidersRequest beta_settings_service_get_active_identity_providers_request) -> Models::BetaSettingsServiceGetActiveIdentityProvidersResponse
      def get_active_identity_providers_with_http_info: (Models::BetaSettingsServiceGetActiveIdentityProvidersRequest beta_settings_service_get_active_identity_providers_request) -> ::Zitadel::Client::ApiResult[Models::BetaSettingsServiceGetActiveIdentityProvidersResponse]
      def get_branding_settings: (Models::BetaSettingsServiceGetBrandingSettingsRequest beta_settings_service_get_branding_settings_request) -> Models::BetaSettingsServiceGetBrandingSettingsResponse
      def get_branding_settings_with_http_info: (Models::BetaSettingsServiceGetBrandingSettingsRequest beta_settings_service_get_branding_settings_request) -> ::Zitadel::Client::ApiResult[Models::BetaSettingsServiceGetBrandingSettingsResponse]
      def get_domain_settings: (Models::BetaSettingsServiceGetDomainSettingsRequest beta_settings_service_get_domain_settings_request) -> Models::BetaSettingsServiceGetDomainSettingsResponse
      def get_domain_settings_with_http_info: (Models::BetaSettingsServiceGetDomainSettingsRequest beta_settings_service_get_domain_settings_request) -> ::Zitadel::Client::ApiResult[Models::BetaSettingsServiceGetDomainSettingsResponse]
      def get_general_settings: (untyped body) -> Models::BetaSettingsServiceGetGeneralSettingsResponse
      def get_general_settings_with_http_info: (untyped body) -> ::Zitadel::Client::ApiResult[Models::BetaSettingsServiceGetGeneralSettingsResponse]
      def get_legal_and_support_settings: (Models::BetaSettingsServiceGetLegalAndSupportSettingsRequest beta_settings_service_get_legal_and_support_settings_request) -> Models::BetaSettingsServiceGetLegalAndSupportSettingsResponse
      def get_legal_and_support_settings_with_http_info: (Models::BetaSettingsServiceGetLegalAndSupportSettingsRequest beta_settings_service_get_legal_and_support_settings_request) -> ::Zitadel::Client::ApiResult[Models::BetaSettingsServiceGetLegalAndSupportSettingsResponse]
      def get_lockout_settings: (Models::BetaSettingsServiceGetLockoutSettingsRequest beta_settings_service_get_lockout_settings_request) -> Models::BetaSettingsServiceGetLockoutSettingsResponse
      def get_lockout_settings_with_http_info: (Models::BetaSettingsServiceGetLockoutSettingsRequest beta_settings_service_get_lockout_settings_request) -> ::Zitadel::Client::ApiResult[Models::BetaSettingsServiceGetLockoutSettingsResponse]
      def get_login_settings: (Models::BetaSettingsServiceGetLoginSettingsRequest beta_settings_service_get_login_settings_request) -> Models::BetaSettingsServiceGetLoginSettingsResponse
      def get_login_settings_with_http_info: (Models::BetaSettingsServiceGetLoginSettingsRequest beta_settings_service_get_login_settings_request) -> ::Zitadel::Client::ApiResult[Models::BetaSettingsServiceGetLoginSettingsResponse]
      def get_password_complexity_settings: (Models::BetaSettingsServiceGetPasswordComplexitySettingsRequest beta_settings_service_get_password_complexity_settings_request) -> Models::BetaSettingsServiceGetPasswordComplexitySettingsResponse
      def get_password_complexity_settings_with_http_info: (Models::BetaSettingsServiceGetPasswordComplexitySettingsRequest beta_settings_service_get_password_complexity_settings_request) -> ::Zitadel::Client::ApiResult[Models::BetaSettingsServiceGetPasswordComplexitySettingsResponse]
      def get_password_expiry_settings: (Models::BetaSettingsServiceGetPasswordExpirySettingsRequest beta_settings_service_get_password_expiry_settings_request) -> Models::BetaSettingsServiceGetPasswordExpirySettingsResponse
      def get_password_expiry_settings_with_http_info: (Models::BetaSettingsServiceGetPasswordExpirySettingsRequest beta_settings_service_get_password_expiry_settings_request) -> ::Zitadel::Client::ApiResult[Models::BetaSettingsServiceGetPasswordExpirySettingsResponse]
      def get_security_settings: (untyped body) -> Models::BetaSettingsServiceGetSecuritySettingsResponse
      def get_security_settings_with_http_info: (untyped body) -> ::Zitadel::Client::ApiResult[Models::BetaSettingsServiceGetSecuritySettingsResponse]
      def set_security_settings: (Models::BetaSettingsServiceSetSecuritySettingsRequest beta_settings_service_set_security_settings_request) -> Models::BetaSettingsServiceSetSecuritySettingsResponse
      def set_security_settings_with_http_info: (Models::BetaSettingsServiceSetSecuritySettingsRequest beta_settings_service_set_security_settings_request) -> ::Zitadel::Client::ApiResult[Models::BetaSettingsServiceSetSecuritySettingsResponse]
    end
  end
end
