module Zitadel::Client
  module Api
    class UserServiceApi < BaseApi
      def initialize: (?::Zitadel::Client::ApiClient? api_client, ?::Zitadel::Client::Configuration config, ?::Zitadel::Client::Auth::Authenticator? authenticator) -> void
      def add_human_user: (Models::UserServiceAddHumanUserRequest user_service_add_human_user_request) -> Models::UserServiceAddHumanUserResponse
      def add_human_user_with_http_info: (Models::UserServiceAddHumanUserRequest user_service_add_human_user_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceAddHumanUserResponse]
      def add_idp_link: (Models::UserServiceAddIDPLinkRequest user_service_add_idp_link_request) -> Models::UserServiceAddIDPLinkResponse
      def add_idp_link_with_http_info: (Models::UserServiceAddIDPLinkRequest user_service_add_idp_link_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceAddIDPLinkResponse]
      def add_key: (Models::UserServiceAddKeyRequest user_service_add_key_request) -> Models::UserServiceAddKeyResponse
      def add_key_with_http_info: (Models::UserServiceAddKeyRequest user_service_add_key_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceAddKeyResponse]
      def add_otp_email: (Models::UserServiceAddOTPEmailRequest user_service_add_otp_email_request) -> Models::UserServiceAddOTPEmailResponse
      def add_otp_email_with_http_info: (Models::UserServiceAddOTPEmailRequest user_service_add_otp_email_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceAddOTPEmailResponse]
      def add_otpsms: (Models::UserServiceAddOTPSMSRequest user_service_add_otpsms_request) -> Models::UserServiceAddOTPSMSResponse
      def add_otpsms_with_http_info: (Models::UserServiceAddOTPSMSRequest user_service_add_otpsms_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceAddOTPSMSResponse]
      def add_personal_access_token: (Models::UserServiceAddPersonalAccessTokenRequest user_service_add_personal_access_token_request) -> Models::UserServiceAddPersonalAccessTokenResponse
      def add_personal_access_token_with_http_info: (Models::UserServiceAddPersonalAccessTokenRequest user_service_add_personal_access_token_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceAddPersonalAccessTokenResponse]
      def add_secret: (Models::UserServiceAddSecretRequest user_service_add_secret_request) -> Models::UserServiceAddSecretResponse
      def add_secret_with_http_info: (Models::UserServiceAddSecretRequest user_service_add_secret_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceAddSecretResponse]
      def create_invite_code: (Models::UserServiceCreateInviteCodeRequest user_service_create_invite_code_request) -> Models::UserServiceCreateInviteCodeResponse
      def create_invite_code_with_http_info: (Models::UserServiceCreateInviteCodeRequest user_service_create_invite_code_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceCreateInviteCodeResponse]
      def create_passkey_registration_link: (Models::UserServiceCreatePasskeyRegistrationLinkRequest user_service_create_passkey_registration_link_request) -> Models::UserServiceCreatePasskeyRegistrationLinkResponse
      def create_passkey_registration_link_with_http_info: (Models::UserServiceCreatePasskeyRegistrationLinkRequest user_service_create_passkey_registration_link_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceCreatePasskeyRegistrationLinkResponse]
      def create_user: (Models::UserServiceCreateUserRequest user_service_create_user_request) -> Models::UserServiceCreateUserResponse
      def create_user_with_http_info: (Models::UserServiceCreateUserRequest user_service_create_user_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceCreateUserResponse]
      def deactivate_user: (Models::UserServiceDeactivateUserRequest user_service_deactivate_user_request) -> Models::UserServiceDeactivateUserResponse
      def deactivate_user_with_http_info: (Models::UserServiceDeactivateUserRequest user_service_deactivate_user_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceDeactivateUserResponse]
      def delete_user: (Models::UserServiceDeleteUserRequest user_service_delete_user_request) -> Models::UserServiceDeleteUserResponse
      def delete_user_with_http_info: (Models::UserServiceDeleteUserRequest user_service_delete_user_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceDeleteUserResponse]
      def delete_user_metadata: (Models::UserServiceDeleteUserMetadataRequest user_service_delete_user_metadata_request) -> Models::UserServiceDeleteUserMetadataResponse
      def delete_user_metadata_with_http_info: (Models::UserServiceDeleteUserMetadataRequest user_service_delete_user_metadata_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceDeleteUserMetadataResponse]
      def generate_recovery_codes: (Models::UserServiceGenerateRecoveryCodesRequest user_service_generate_recovery_codes_request) -> Models::UserServiceGenerateRecoveryCodesResponse
      def generate_recovery_codes_with_http_info: (Models::UserServiceGenerateRecoveryCodesRequest user_service_generate_recovery_codes_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceGenerateRecoveryCodesResponse]
      def get_user_by_id: (Models::UserServiceGetUserByIDRequest user_service_get_user_by_id_request) -> Models::UserServiceGetUserByIDResponse
      def get_user_by_id_with_http_info: (Models::UserServiceGetUserByIDRequest user_service_get_user_by_id_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceGetUserByIDResponse]
      def human_mfa_init_skipped: (Models::UserServiceHumanMFAInitSkippedRequest user_service_human_mfa_init_skipped_request) -> Models::UserServiceHumanMFAInitSkippedResponse
      def human_mfa_init_skipped_with_http_info: (Models::UserServiceHumanMFAInitSkippedRequest user_service_human_mfa_init_skipped_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceHumanMFAInitSkippedResponse]
      def list_authentication_factors: (Models::UserServiceListAuthenticationFactorsRequest user_service_list_authentication_factors_request) -> Models::UserServiceListAuthenticationFactorsResponse
      def list_authentication_factors_with_http_info: (Models::UserServiceListAuthenticationFactorsRequest user_service_list_authentication_factors_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceListAuthenticationFactorsResponse]
      def list_authentication_method_types: (Models::UserServiceListAuthenticationMethodTypesRequest user_service_list_authentication_method_types_request) -> Models::UserServiceListAuthenticationMethodTypesResponse
      def list_authentication_method_types_with_http_info: (Models::UserServiceListAuthenticationMethodTypesRequest user_service_list_authentication_method_types_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceListAuthenticationMethodTypesResponse]
      def list_idp_links: (Models::UserServiceListIDPLinksRequest user_service_list_idp_links_request) -> Models::UserServiceListIDPLinksResponse
      def list_idp_links_with_http_info: (Models::UserServiceListIDPLinksRequest user_service_list_idp_links_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceListIDPLinksResponse]
      def list_keys: (Models::UserServiceListKeysRequest user_service_list_keys_request) -> Models::UserServiceListKeysResponse
      def list_keys_with_http_info: (Models::UserServiceListKeysRequest user_service_list_keys_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceListKeysResponse]
      def list_passkeys: (Models::UserServiceListPasskeysRequest user_service_list_passkeys_request) -> Models::UserServiceListPasskeysResponse
      def list_passkeys_with_http_info: (Models::UserServiceListPasskeysRequest user_service_list_passkeys_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceListPasskeysResponse]
      def list_personal_access_tokens: (Models::UserServiceListPersonalAccessTokensRequest user_service_list_personal_access_tokens_request) -> Models::UserServiceListPersonalAccessTokensResponse
      def list_personal_access_tokens_with_http_info: (Models::UserServiceListPersonalAccessTokensRequest user_service_list_personal_access_tokens_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceListPersonalAccessTokensResponse]
      def list_user_metadata: (Models::UserServiceListUserMetadataRequest user_service_list_user_metadata_request) -> Models::UserServiceListUserMetadataResponse
      def list_user_metadata_with_http_info: (Models::UserServiceListUserMetadataRequest user_service_list_user_metadata_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceListUserMetadataResponse]
      def list_users: (Models::UserServiceListUsersRequest user_service_list_users_request) -> Models::UserServiceListUsersResponse
      def list_users_with_http_info: (Models::UserServiceListUsersRequest user_service_list_users_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceListUsersResponse]
      def lock_user: (Models::UserServiceLockUserRequest user_service_lock_user_request) -> Models::UserServiceLockUserResponse
      def lock_user_with_http_info: (Models::UserServiceLockUserRequest user_service_lock_user_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceLockUserResponse]
      def password_reset: (Models::UserServicePasswordResetRequest user_service_password_reset_request) -> Models::UserServicePasswordResetResponse
      def password_reset_with_http_info: (Models::UserServicePasswordResetRequest user_service_password_reset_request) -> ::Zitadel::Client::ApiResult[Models::UserServicePasswordResetResponse]
      def reactivate_user: (Models::UserServiceReactivateUserRequest user_service_reactivate_user_request) -> Models::UserServiceReactivateUserResponse
      def reactivate_user_with_http_info: (Models::UserServiceReactivateUserRequest user_service_reactivate_user_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceReactivateUserResponse]
      def register_passkey: (Models::UserServiceRegisterPasskeyRequest user_service_register_passkey_request) -> Models::UserServiceRegisterPasskeyResponse
      def register_passkey_with_http_info: (Models::UserServiceRegisterPasskeyRequest user_service_register_passkey_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceRegisterPasskeyResponse]
      def register_totp: (Models::UserServiceRegisterTOTPRequest user_service_register_totp_request) -> Models::UserServiceRegisterTOTPResponse
      def register_totp_with_http_info: (Models::UserServiceRegisterTOTPRequest user_service_register_totp_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceRegisterTOTPResponse]
      def register_u2_f: (Models::UserServiceRegisterU2FRequest user_service_register_u2_f_request) -> Models::UserServiceRegisterU2FResponse
      def register_u2_f_with_http_info: (Models::UserServiceRegisterU2FRequest user_service_register_u2_f_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceRegisterU2FResponse]
      def remove_idp_link: (Models::UserServiceRemoveIDPLinkRequest user_service_remove_idp_link_request) -> Models::UserServiceRemoveIDPLinkResponse
      def remove_idp_link_with_http_info: (Models::UserServiceRemoveIDPLinkRequest user_service_remove_idp_link_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceRemoveIDPLinkResponse]
      def remove_key: (Models::UserServiceRemoveKeyRequest user_service_remove_key_request) -> Models::UserServiceRemoveKeyResponse
      def remove_key_with_http_info: (Models::UserServiceRemoveKeyRequest user_service_remove_key_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceRemoveKeyResponse]
      def remove_otp_email: (Models::UserServiceRemoveOTPEmailRequest user_service_remove_otp_email_request) -> Models::UserServiceRemoveOTPEmailResponse
      def remove_otp_email_with_http_info: (Models::UserServiceRemoveOTPEmailRequest user_service_remove_otp_email_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceRemoveOTPEmailResponse]
      def remove_otpsms: (Models::UserServiceRemoveOTPSMSRequest user_service_remove_otpsms_request) -> Models::UserServiceRemoveOTPSMSResponse
      def remove_otpsms_with_http_info: (Models::UserServiceRemoveOTPSMSRequest user_service_remove_otpsms_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceRemoveOTPSMSResponse]
      def remove_passkey: (Models::UserServiceRemovePasskeyRequest user_service_remove_passkey_request) -> Models::UserServiceRemovePasskeyResponse
      def remove_passkey_with_http_info: (Models::UserServiceRemovePasskeyRequest user_service_remove_passkey_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceRemovePasskeyResponse]
      def remove_personal_access_token: (Models::UserServiceRemovePersonalAccessTokenRequest user_service_remove_personal_access_token_request) -> Models::UserServiceRemovePersonalAccessTokenResponse
      def remove_personal_access_token_with_http_info: (Models::UserServiceRemovePersonalAccessTokenRequest user_service_remove_personal_access_token_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceRemovePersonalAccessTokenResponse]
      def remove_phone: (Models::UserServiceRemovePhoneRequest user_service_remove_phone_request) -> Models::UserServiceRemovePhoneResponse
      def remove_phone_with_http_info: (Models::UserServiceRemovePhoneRequest user_service_remove_phone_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceRemovePhoneResponse]
      def remove_recovery_codes: (Models::UserServiceRemoveRecoveryCodesRequest user_service_remove_recovery_codes_request) -> Models::UserServiceRemoveRecoveryCodesResponse
      def remove_recovery_codes_with_http_info: (Models::UserServiceRemoveRecoveryCodesRequest user_service_remove_recovery_codes_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceRemoveRecoveryCodesResponse]
      def remove_secret: (Models::UserServiceRemoveSecretRequest user_service_remove_secret_request) -> Models::UserServiceRemoveSecretResponse
      def remove_secret_with_http_info: (Models::UserServiceRemoveSecretRequest user_service_remove_secret_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceRemoveSecretResponse]
      def remove_totp: (Models::UserServiceRemoveTOTPRequest user_service_remove_totp_request) -> Models::UserServiceRemoveTOTPResponse
      def remove_totp_with_http_info: (Models::UserServiceRemoveTOTPRequest user_service_remove_totp_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceRemoveTOTPResponse]
      def remove_u2_f: (Models::UserServiceRemoveU2FRequest user_service_remove_u2_f_request) -> Models::UserServiceRemoveU2FResponse
      def remove_u2_f_with_http_info: (Models::UserServiceRemoveU2FRequest user_service_remove_u2_f_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceRemoveU2FResponse]
      def resend_email_code: (Models::UserServiceResendEmailCodeRequest user_service_resend_email_code_request) -> Models::UserServiceResendEmailCodeResponse
      def resend_email_code_with_http_info: (Models::UserServiceResendEmailCodeRequest user_service_resend_email_code_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceResendEmailCodeResponse]
      def resend_invite_code: (Models::UserServiceResendInviteCodeRequest user_service_resend_invite_code_request) -> Models::UserServiceResendInviteCodeResponse
      def resend_invite_code_with_http_info: (Models::UserServiceResendInviteCodeRequest user_service_resend_invite_code_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceResendInviteCodeResponse]
      def resend_phone_code: (Models::UserServiceResendPhoneCodeRequest user_service_resend_phone_code_request) -> Models::UserServiceResendPhoneCodeResponse
      def resend_phone_code_with_http_info: (Models::UserServiceResendPhoneCodeRequest user_service_resend_phone_code_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceResendPhoneCodeResponse]
      def retrieve_identity_provider_intent: (Models::UserServiceRetrieveIdentityProviderIntentRequest user_service_retrieve_identity_provider_intent_request) -> Models::UserServiceRetrieveIdentityProviderIntentResponse
      def retrieve_identity_provider_intent_with_http_info: (Models::UserServiceRetrieveIdentityProviderIntentRequest user_service_retrieve_identity_provider_intent_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceRetrieveIdentityProviderIntentResponse]
      def send_email_code: (Models::UserServiceSendEmailCodeRequest user_service_send_email_code_request) -> Models::UserServiceSendEmailCodeResponse
      def send_email_code_with_http_info: (Models::UserServiceSendEmailCodeRequest user_service_send_email_code_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceSendEmailCodeResponse]
      def set_email: (Models::UserServiceSetEmailRequest user_service_set_email_request) -> Models::UserServiceSetEmailResponse
      def set_email_with_http_info: (Models::UserServiceSetEmailRequest user_service_set_email_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceSetEmailResponse]
      def set_password: (Models::UserServiceSetPasswordRequest user_service_set_password_request) -> Models::UserServiceSetPasswordResponse
      def set_password_with_http_info: (Models::UserServiceSetPasswordRequest user_service_set_password_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceSetPasswordResponse]
      def set_phone: (Models::UserServiceSetPhoneRequest user_service_set_phone_request) -> Models::UserServiceSetPhoneResponse
      def set_phone_with_http_info: (Models::UserServiceSetPhoneRequest user_service_set_phone_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceSetPhoneResponse]
      def set_user_metadata: (Models::UserServiceSetUserMetadataRequest user_service_set_user_metadata_request) -> Models::UserServiceSetUserMetadataResponse
      def set_user_metadata_with_http_info: (Models::UserServiceSetUserMetadataRequest user_service_set_user_metadata_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceSetUserMetadataResponse]
      def start_identity_provider_intent: (Models::UserServiceStartIdentityProviderIntentRequest user_service_start_identity_provider_intent_request) -> Models::UserServiceStartIdentityProviderIntentResponse
      def start_identity_provider_intent_with_http_info: (Models::UserServiceStartIdentityProviderIntentRequest user_service_start_identity_provider_intent_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceStartIdentityProviderIntentResponse]
      def unlock_user: (Models::UserServiceUnlockUserRequest user_service_unlock_user_request) -> Models::UserServiceUnlockUserResponse
      def unlock_user_with_http_info: (Models::UserServiceUnlockUserRequest user_service_unlock_user_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceUnlockUserResponse]
      def update_human_user: (Models::UserServiceUpdateHumanUserRequest user_service_update_human_user_request) -> Models::UserServiceUpdateHumanUserResponse
      def update_human_user_with_http_info: (Models::UserServiceUpdateHumanUserRequest user_service_update_human_user_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceUpdateHumanUserResponse]
      def update_user: (Models::UserServiceUpdateUserRequest user_service_update_user_request) -> Models::UserServiceUpdateUserResponse
      def update_user_with_http_info: (Models::UserServiceUpdateUserRequest user_service_update_user_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceUpdateUserResponse]
      def verify_email: (Models::UserServiceVerifyEmailRequest user_service_verify_email_request) -> Models::UserServiceVerifyEmailResponse
      def verify_email_with_http_info: (Models::UserServiceVerifyEmailRequest user_service_verify_email_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceVerifyEmailResponse]
      def verify_invite_code: (Models::UserServiceVerifyInviteCodeRequest user_service_verify_invite_code_request) -> Models::UserServiceVerifyInviteCodeResponse
      def verify_invite_code_with_http_info: (Models::UserServiceVerifyInviteCodeRequest user_service_verify_invite_code_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceVerifyInviteCodeResponse]
      def verify_passkey_registration: (Models::UserServiceVerifyPasskeyRegistrationRequest user_service_verify_passkey_registration_request) -> Models::UserServiceVerifyPasskeyRegistrationResponse
      def verify_passkey_registration_with_http_info: (Models::UserServiceVerifyPasskeyRegistrationRequest user_service_verify_passkey_registration_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceVerifyPasskeyRegistrationResponse]
      def verify_phone: (Models::UserServiceVerifyPhoneRequest user_service_verify_phone_request) -> Models::UserServiceVerifyPhoneResponse
      def verify_phone_with_http_info: (Models::UserServiceVerifyPhoneRequest user_service_verify_phone_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceVerifyPhoneResponse]
      def verify_totp_registration: (Models::UserServiceVerifyTOTPRegistrationRequest user_service_verify_totp_registration_request) -> Models::UserServiceVerifyTOTPRegistrationResponse
      def verify_totp_registration_with_http_info: (Models::UserServiceVerifyTOTPRegistrationRequest user_service_verify_totp_registration_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceVerifyTOTPRegistrationResponse]
      def verify_u2_f_registration: (Models::UserServiceVerifyU2FRegistrationRequest user_service_verify_u2_f_registration_request) -> Models::UserServiceVerifyU2FRegistrationResponse
      def verify_u2_f_registration_with_http_info: (Models::UserServiceVerifyU2FRegistrationRequest user_service_verify_u2_f_registration_request) -> ::Zitadel::Client::ApiResult[Models::UserServiceVerifyU2FRegistrationResponse]
    end
  end
end
