# frozen_string_literal: true

# rubocop:disable all
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

module Zitadel::Client
  module Auth
    # Base class for providing authentication credentials to the API client.
    # Subclasses supply the API host URL and authorization headers.
    class Authenticator
      # Returns the base URL of the API.
      # @return [String]
      def host
        raise NotImplementedError, "#{self.class}#host must be implemented"
      end

      # Returns the authentication headers to include in every request.
      # @return [Hash{String => String}]
      def auth_headers
        raise NotImplementedError, "#{self.class}#auth_headers must be implemented"
      end

      # Returns query parameters to include for authentication.
      # @return [Hash{String => String}]
      def query_params
        {}
      end

      # Returns cookie parameters to include for authentication.
      # @return [Hash{String => String}]
      def cookie_params
        {}
      end
    end
  end
end
