module Zitadel::Client::Models
  class ActionServiceListExecutionsResponse < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader pagination: ActionServicePaginationResponse?
    attr_reader executions: Array[ActionServiceExecution]?
  end
end
