module Zitadel::Client::Models
  class ActionServiceListPublicKeysResponse < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader pagination: ActionServicePaginationResponse?
    attr_reader public_keys: Array[ActionServicePublicKey]?
  end
end
