module Zitadel::Client::Models
  class ActionServiceListPublicKeysRequest < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader target_id: String?
    attr_reader pagination: ActionServicePaginationRequest?
    attr_reader sorting_column: ActionServicePublicKeyFieldName?
    attr_reader filters: Array[ActionServicePublicKeySearchFilter]?
  end
end
