module Zitadel::Client::Models
  class ActionServiceCondition < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader event: ActionServiceEventExecution?
    attr_reader function: ActionServiceFunctionExecution?
    attr_reader request: ActionServiceRequestExecution?
    attr_reader response: ActionServiceResponseExecution?
  end
end
