module Zitadel::Client::Models
  class ApplicationServiceOIDCGrantType
    OIDC_GRANT_TYPE_AUTHORIZATION_CODE: String
    OIDC_GRANT_TYPE_IMPLICIT: String
    OIDC_GRANT_TYPE_REFRESH_TOKEN: String
    OIDC_GRANT_TYPE_DEVICE_CODE: String
    OIDC_GRANT_TYPE_TOKEN_EXCHANGE: String
    VALUES: Array[String]
    def self.all_vars: () -> Array[String]
    def self.validate!: (String?) -> String?
  end
end
