module Zitadel::Client::Models
  class ApplicationServiceListApplicationKeysRequest < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader pagination: ApplicationServicePaginationRequest?
    attr_reader sorting_column: ApplicationServiceApplicationKeysSorting?
    attr_reader filters: Array[ApplicationServiceApplicationKeySearchFilter]?
  end
end
