module Zitadel::Client::Models
  class ApplicationServiceOIDCLocalizedMessage < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader key: String?
    attr_reader localized_message: String?
  end
end
