module Zitadel::Client::Models
  class ApplicationServiceOIDCTokenType
    OIDC_TOKEN_TYPE_BEARER: String
    OIDC_TOKEN_TYPE_JWT: String
    VALUES: Array[String]
    def self.all_vars: () -> Array[String]
    def self.validate!: (String?) -> String?
  end
end
