module Zitadel::Client::Models
  class ApplicationServiceCreateApplicationResponse < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader application_id: String?
    attr_reader creation_date: Time?
    attr_reader api_configuration: ApplicationServiceCreateAPIApplicationResponse?
    attr_reader oidc_configuration: ApplicationServiceCreateOIDCApplicationResponse?
    attr_reader saml_configuration: untyped?
  end
end
