module Zitadel::Client::Models
  class ApplicationServiceApplication < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader application_id: String?
    attr_reader creation_date: Time?
    attr_reader change_date: Time?
    attr_reader state: ApplicationServiceApplicationState?
    attr_reader name: String?
    attr_reader project_id: String?
    attr_reader api_configuration: ApplicationServiceAPIConfiguration?
    attr_reader oidc_configuration: ApplicationServiceOIDCConfiguration?
    attr_reader saml_configuration: ApplicationServiceSAMLConfiguration?
  end
end
