module Zitadel::Client::Models
  class BetaInstanceServiceListTrustedDomainsRequest < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader instance_id: String?
    attr_reader pagination: BetaInstanceServicePaginationRequest?
    attr_reader sorting_column: BetaInstanceServiceTrustedDomainFieldName?
    attr_reader queries: Array[BetaInstanceServiceTrustedDomainSearchQuery]?
  end
end
