module Zitadel::Client::Models
  class BetaProjectServiceListProjectGrantsRequest < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader pagination: BetaProjectServicePaginationRequest?
    attr_reader sorting_column: BetaProjectServiceProjectGrantFieldName?
    attr_reader filters: Array[BetaProjectServiceProjectGrantSearchFilter]?
  end
end
