module Zitadel::Client::Models
  class BetaProjectServiceProject < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader id: String?
    attr_reader organization_id: String?
    attr_reader creation_date: Time?
    attr_reader change_date: Time?
    attr_reader name: String?
    attr_reader state: BetaProjectServiceProjectState?
    attr_reader project_role_assertion: bool?
    attr_reader authorization_required: bool?
    attr_reader project_access_required: bool?
    attr_reader private_labeling_setting: BetaProjectServicePrivateLabelingSetting?
    attr_reader granted_organization_id: String?
    attr_reader granted_organization_name: String?
    attr_reader granted_state: BetaProjectServiceGrantedProjectState?
  end
end
