module Zitadel::Client::Models
  class BetaUserServiceStartIdentityProviderIntentRequest < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader idp_id: String?
    attr_reader ldap: BetaUserServiceLDAPCredentials?
    attr_reader urls: BetaUserServiceRedirectURLs?
  end
end
