module Zitadel::Client::Models
  class BetaUserServiceUser < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader user_id: String?
    attr_reader details: BetaUserServiceDetails?
    attr_reader state: BetaUserServiceUserState?
    attr_reader username: String?
    attr_reader login_names: Array[String]?
    attr_reader preferred_login_name: String?
    attr_reader human: BetaUserServiceHumanUser?
    attr_reader machine: BetaUserServiceMachineUser?
  end
end
