module Zitadel::Client::Models
  class BetaOrganizationServiceDomainValidationType
    DOMAIN_VALIDATION_TYPE_UNSPECIFIED: String
    DOMAIN_VALIDATION_TYPE_HTTP: String
    DOMAIN_VALIDATION_TYPE_DNS: String
    VALUES: Array[String]
    def self.all_vars: () -> Array[String]
    def self.validate!: (String?) -> String?
  end
end
