module Zitadel::Client::Models
  class BetaTelemetryServiceReportBaseInformationRequest < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader system_id: String?
    attr_reader version: String?
    attr_reader instances: Array[BetaTelemetryServiceInstanceInformation]?
  end
end
