module Zitadel::Client::Models
  class BetaInstanceServiceListCustomDomainsResponse < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader domains: Array[BetaInstanceServiceDomain]?
    attr_reader pagination: BetaInstanceServicePaginationResponse?
  end
end
