module Zitadel::Client::Models
  class BetaActionServiceTargetSearchFilter < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader in_target_ids_filter: BetaActionServiceInTargetIDsFilter?
    attr_reader target_name_filter: BetaActionServiceTargetNameFilter?
  end
end
