module Zitadel::Client::Models
  class BetaInternalPermissionServiceResourceType < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader instance: bool?
    attr_reader organization_id: String?
    attr_reader project_grant: BetaInternalPermissionServiceProjectGrant?
    attr_reader project_id: String?
  end
end
