module Zitadel::Client::Models
  class BetaUserServiceSendPasswordResetLink < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader notification_type: BetaUserServiceNotificationType?
    attr_reader url_template: String?
  end
end
