module Zitadel::Client::Models
  class BetaAuthorizationServiceState
    STATE_UNSPECIFIED: String
    STATE_ACTIVE: String
    STATE_INACTIVE: String
    VALUES: Array[String]
    def self.all_vars: () -> Array[String]
    def self.validate!: (String?) -> String?
  end
end
