module Zitadel::Client::Models
  class BetaWebKeyServiceListWebKeysResponse < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader web_keys: Array[BetaWebKeyServiceWebKey]?
  end
end
