module Zitadel::Client::Models
  class BetaAppServiceApplicationNameQuery < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader name: String?
    attr_reader method: BetaAppServiceTextFilterMethod?
  end
end
