module Zitadel::Client::Models
  class BetaOrganizationServiceDomain < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader organization_id: String?
    attr_reader domain_name: String?
    attr_reader is_verified: bool?
    attr_reader is_primary: bool?
    attr_reader validation_type: BetaOrganizationServiceDomainValidationType?
  end
end
