module Zitadel::Client::Models
  class BetaUserServiceRegisterPasskeyResponse < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader details: BetaUserServiceDetails?
    attr_reader passkey_id: String?
    attr_reader public_key_credential_creation_options: Hash[String, untyped]?
  end
end
