module Zitadel::Client::Models
  class BetaAuthorizationServiceAuthorizationFieldName
    AUTHORIZATION_FIELD_NAME_UNSPECIFIED: String
    AUTHORIZATION_FIELD_NAME_CREATED_DATE: String
    AUTHORIZATION_FIELD_NAME_CHANGED_DATE: String
    AUTHORIZATION_FIELD_NAME_ID: String
    AUTHORIZATION_FIELD_NAME_USER_ID: String
    AUTHORIZATION_FIELD_NAME_PROJECT_ID: String
    AUTHORIZATION_FIELD_NAME_ORGANIZATION_ID: String
    AUTHORIZATION_FIELD_NAME_USER_ORGANIZATION_ID: String
    VALUES: Array[String]
    def self.all_vars: () -> Array[String]
    def self.validate!: (String?) -> String?
  end
end
