module Zitadel::Client::Models
  class BetaInstanceServiceListInstancesRequest < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader queries: Array[BetaInstanceServiceQuery]?
    attr_reader pagination: BetaInstanceServicePaginationRequest?
    attr_reader sorting_column: BetaInstanceServiceFieldName?
  end
end
