module Zitadel::Client::Models
  class BetaAuthorizationServiceCreateAuthorizationResponse < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader id: String?
    attr_reader creation_date: Time?
  end
end
