module Zitadel::Client::Models
  class BetaSettingsServicePasswordComplexitySettings < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader min_length: untyped?
    attr_reader requires_uppercase: bool?
    attr_reader requires_lowercase: bool?
    attr_reader requires_number: bool?
    attr_reader requires_symbol: bool?
    attr_reader resource_owner_type: BetaSettingsServiceResourceOwnerType?
  end
end
