module Zitadel::Client::Models
  class BetaFeatureServiceGetInstanceFeaturesResponse < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader details: BetaFeatureServiceDetails?
    attr_reader login_default_org: BetaFeatureServiceFeatureFlag?
    attr_reader user_schema: BetaFeatureServiceFeatureFlag?
    attr_reader oidc_token_exchange: BetaFeatureServiceFeatureFlag?
    attr_reader improved_performance: BetaFeatureServiceImprovedPerformanceFeatureFlag?
    attr_reader debug_oidc_parent_error: BetaFeatureServiceFeatureFlag?
    attr_reader oidc_single_v1_session_termination: BetaFeatureServiceFeatureFlag?
  end
end
