module Zitadel::Client::Models
  class BetaTelemetryServiceReportResourceCountsRequest < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader system_id: String?
    attr_reader report_id: String?
    attr_reader resource_counts: Array[BetaTelemetryServiceResourceCount]?
  end
end
