module Zitadel::Client::Models
  class FeatureServiceSetInstanceFeaturesRequest < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader login_default_org: bool?
    attr_reader user_schema: bool?
    attr_reader oidc_token_exchange: bool?
    attr_reader improved_performance: Array[FeatureServiceImprovedPerformance]?
    attr_reader debug_oidc_parent_error: bool?
    attr_reader oidc_single_v1_session_termination: bool?
    attr_reader enable_back_channel_logout: bool?
    attr_reader login_v2: FeatureServiceLoginV2?
    attr_reader permission_check_v2: bool?
    attr_reader console_use_v2_user_api: bool?
  end
end
