module Zitadel::Client::Models
  class FeatureServiceLoginV2 < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader required: bool?
    attr_reader base_uri: String?
  end
end
