module Zitadel::Client::Models
  class IdentityProviderServiceAzureADTenant < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader tenant_id: String?
    attr_reader tenant_type: IdentityProviderServiceAzureADTenantType?
  end
end
