module Zitadel::Client::Models
  class InstanceServiceRemoveCustomDomainRequest < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader instance_id: String?
    attr_reader custom_domain: String?
  end
end
