module Zitadel::Client::Models
  class InternalPermissionServiceUserPreferredLoginNameFilter < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader preferred_login_name: String?
    attr_reader method: InternalPermissionServiceTextFilterMethod?
  end
end
