module Zitadel::Client::Models
  class InternalPermissionServiceUpdateAdministratorRequest < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader user_id: String?
    attr_reader resource: InternalPermissionServiceResourceType?
    attr_reader roles: Array[String]?
  end
end
