module Zitadel::Client::Models
  class InternalPermissionServiceAdministrator < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader creation_date: Time?
    attr_reader change_date: Time?
    attr_reader user: InternalPermissionServiceUser?
    attr_reader roles: Array[String]?
    attr_reader instance: bool?
    attr_reader organization: InternalPermissionServiceOrganization?
    attr_reader project: InternalPermissionServiceProject?
    attr_reader project_grant: InternalPermissionServiceProjectGrant?
  end
end
