module Zitadel::Client::Models
  class OIDCServiceCreateCallbackResponse < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader details: OIDCServiceDetails?
    attr_reader callback_url: String?
  end
end
