module Zitadel::Client::Models
  class OIDCServiceErrorReason
    ERROR_REASON_UNSPECIFIED: String
    ERROR_REASON_INVALID_REQUEST: String
    ERROR_REASON_UNAUTHORIZED_CLIENT: String
    ERROR_REASON_ACCESS_DENIED: String
    ERROR_REASON_UNSUPPORTED_RESPONSE_TYPE: String
    ERROR_REASON_INVALID_SCOPE: String
    ERROR_REASON_SERVER_ERROR: String
    ERROR_REASON_TEMPORARY_UNAVAILABLE: String
    ERROR_REASON_INTERACTION_REQUIRED: String
    ERROR_REASON_LOGIN_REQUIRED: String
    ERROR_REASON_ACCOUNT_SELECTION_REQUIRED: String
    ERROR_REASON_CONSENT_REQUIRED: String
    ERROR_REASON_INVALID_REQUEST_URI: String
    ERROR_REASON_INVALID_REQUEST_OBJECT: String
    ERROR_REASON_REQUEST_NOT_SUPPORTED: String
    ERROR_REASON_REQUEST_URI_NOT_SUPPORTED: String
    ERROR_REASON_REGISTRATION_NOT_SUPPORTED: String
    VALUES: Array[String]
    def self.all_vars: () -> Array[String]
    def self.validate!: (String?) -> String?
  end
end
