module Zitadel::Client::Models
  class ProjectServiceActivateProjectGrantRequest < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader project_id: String?
    attr_reader granted_organization_id: String?
  end
end
