module Zitadel::Client::Models
  class ProjectServiceListProjectRolesResponse < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader pagination: ProjectServicePaginationResponse?
    attr_reader project_roles: Array[ProjectServiceProjectRole]?
  end
end
