module Zitadel::Client::Models
  class ProjectServiceListProjectsRequest < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader pagination: ProjectServicePaginationRequest?
    attr_reader sorting_column: ProjectServiceProjectFieldName?
    attr_reader filters: Array[ProjectServiceProjectSearchFilter]?
  end
end
