module Zitadel::Client::Models
  class ProjectServiceProjectSearchFilter < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader in_project_ids_filter: ProjectServiceInIDsFilter?
    attr_reader organization_id_filter: ProjectServiceProjectOrganizationIDFilter?
    attr_reader project_name_filter: ProjectServiceProjectNameFilter?
  end
end
