module Zitadel::Client::Models
  class SessionServiceListSessionsResponse < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader details: SessionServiceListDetails?
    attr_reader sessions: Array[SessionServiceSession]?
  end
end
