module Zitadel::Client::Models
  class SessionServiceTimestampQueryMethod
    TIMESTAMP_QUERY_METHOD_EQUALS: String
    TIMESTAMP_QUERY_METHOD_GREATER: String
    TIMESTAMP_QUERY_METHOD_GREATER_OR_EQUALS: String
    TIMESTAMP_QUERY_METHOD_LESS: String
    TIMESTAMP_QUERY_METHOD_LESS_OR_EQUALS: String
    VALUES: Array[String]
    def self.all_vars: () -> Array[String]
    def self.validate!: (String?) -> String?
  end
end
