module Zitadel::Client::Models
  class SessionServiceSearchQuery < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader creation_date_query: SessionServiceCreationDateQuery?
    attr_reader creator_query: SessionServiceCreatorQuery?
    attr_reader expiration_date_query: SessionServiceExpirationDateQuery?
    attr_reader ids_query: SessionServiceIDsQuery?
    attr_reader user_agent_query: SessionServiceUserAgentQuery?
    attr_reader user_id_query: SessionServiceUserIDQuery?
  end
end
