module Zitadel::Client::Models
  class SettingsServiceLockoutSettings < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader max_password_attempts: untyped?
    attr_reader resource_owner_type: SettingsServiceResourceOwnerType?
    attr_reader max_otp_attempts: untyped?
  end
end
