module Zitadel::Client::Models
  class SettingsServiceGetHostedLoginTranslationResponse < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader etag: String?
    attr_reader translations: Hash[String, untyped]?
  end
end
