module Zitadel::Client::Models
  class SettingsServiceMultiFactorType
    MULTI_FACTOR_TYPE_UNSPECIFIED: String
    MULTI_FACTOR_TYPE_U2_F_WITH_VERIFICATION: String
    VALUES: Array[String]
    def self.all_vars: () -> Array[String]
    def self.validate!: (String?) -> String?
  end
end
