module Zitadel::Client::Models
  class SettingsServiceGetPasswordComplexitySettingsResponse < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader details: SettingsServiceDetails?
    attr_reader settings: SettingsServicePasswordComplexitySettings?
  end
end
