module Zitadel::Client::Models
  class SettingsServiceRequestContext < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader instance: bool?
    attr_reader org_id: String?
  end
end
