module Zitadel::Client::Models
  class SettingsServiceDomainSettings < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader login_name_includes_domain: bool?
    attr_reader require_org_domain_verification: bool?
    attr_reader smtp_sender_address_matches_instance_domain: bool?
    attr_reader resource_owner_type: SettingsServiceResourceOwnerType?
  end
end
