module Zitadel::Client::Models
  class SettingsServiceEmbeddedIframeSettings < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader enabled: bool?
    attr_reader allowed_origins: Array[String]?
  end
end
