module Zitadel::Client::Models
  class UserServiceTextQueryMethod
    TEXT_QUERY_METHOD_EQUALS: String
    TEXT_QUERY_METHOD_EQUALS_IGNORE_CASE: String
    TEXT_QUERY_METHOD_STARTS_WITH: String
    TEXT_QUERY_METHOD_STARTS_WITH_IGNORE_CASE: String
    TEXT_QUERY_METHOD_CONTAINS: String
    TEXT_QUERY_METHOD_CONTAINS_IGNORE_CASE: String
    TEXT_QUERY_METHOD_ENDS_WITH: String
    TEXT_QUERY_METHOD_ENDS_WITH_IGNORE_CASE: String
    VALUES: Array[String]
    def self.all_vars: () -> Array[String]
    def self.validate!: (String?) -> String?
  end
end
