module Zitadel::Client::Models
  class UserServiceListUserMetadataResponse < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader pagination: UserServicePaginationResponse?
    attr_reader metadata: Array[UserServiceMetadata]?
  end
end
