module Zitadel::Client::Models
  class UserServiceListPersonalAccessTokensRequest < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader pagination: UserServicePaginationRequest?
    attr_reader sorting_column: UserServicePersonalAccessTokenFieldName?
    attr_reader filters: Array[UserServicePersonalAccessTokensSearchFilter]?
  end
end
