module Zitadel::Client::Models
  class UserServiceGenerateRecoveryCodesResponse < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader details: UserServiceDetails?
    attr_reader recovery_codes: Array[String]?
  end
end
