module Zitadel::Client::Models
  class UserServiceStartIdentityProviderIntentRequest < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader idp_id: String?
    attr_reader ldap: UserServiceLDAPCredentials?
    attr_reader urls: UserServiceRedirectURLs?
  end
end
