module Zitadel::Client::Models
  class UserServiceHumanEmail < Dry::Struct
    ATTRIBUTE_MAP: Hash[Symbol, String]
    JSON_KEY_MAP: Hash[String, Symbol]
    OPENAPI_TYPES: Hash[Symbol, String]
    OPENAPI_FORMATS: Hash[Symbol, String]
    attr_reader email: String?
    attr_reader is_verified: bool?
  end
end
