# frozen_string_literal: true

# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

require_relative 'zitadel_error'

module Zitadel::Client
  module Errors
    # Raised when the OAuth2 token endpoint returns a 2xx response that
    # cannot be used: a body that is not a JSON object, or one whose
    # +access_token+ field is missing or empty. Distinct from
    # {OAuth2ServerError} (which represents non-2xx responses) so callers
    # can rescue them separately.
    class OAuth2TokenError < ::Zitadel::Client::Errors::ZitadelError
    end
  end
end
