name: Linting

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      commit_changes:
        required: false
        type: boolean
        default: false

defaults:
  run:
    working-directory: ./

permissions:
  contents: read

jobs:
  lint-format:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: Reformat Code

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@efbf473cab83af4468e8606cc33eca9281bb213f # v1.256.0
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Install Dependencies
        run: bundle install

      - name: Run Formatter
        run: bundle exec rubocop -A --parallel

      - name: Commit Changes
        if: ${{ inputs.commit_changes == true }}
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6.0.1
        with:
          commit_message: 'style: Apply automated code formatting [skip ci]'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
