name: Linting

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      commit_changes:
        required: false
        type: boolean
        default: false

defaults:
  run:
    working-directory: ./

permissions:
  contents: read

jobs:
  lint-format:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    name: Reformat Code

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@13e7a03dc3ac6c3798f4570bfead2aed4d96abfb # v1.244.0
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Install Dependencies
        run: bundle install

      - name: Run Formatter
        run: bundle exec rubocop -A --parallel

      - name: Commit Changes
        if: ${{ inputs.commit_changes == true }}
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5.2.0
        with:
          commit_message: 'style: Apply automated code formatting [skip ci]'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
