name: Release

on:
    push:
        branches:
            - main

permissions:
    contents: write

defaults:
    run:
        working-directory: ./

jobs:
    publish-package:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Set up Ruby
                uses: ruby/setup-ruby@v1
                with:
                    ruby-version: '2.7'
                    bundler-cache: true

            -   name: Install Semantic Release
                run: |
                    npm install --global semantic-release
                    npm install --global @semantic-release/git
                    npm install --global @semantic-release/exec
                    npm install --global semantic-release-rubygem

            -   name: Run semantic-release
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_TOKEN }}
                run: npx semantic-release
