name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - beta

permissions:
  contents: write
  packages: write
  id-token: write
  checks: read

defaults:
  run:
    working-directory: ./

jobs:
  publish-package:
    runs-on: ubuntu-latest
    name: To Artifactory

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64 # v1.299.0
        with:
          bundler-cache: false

      - name: Run semantic-release
        uses: mridang/action-semantic-release@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          DOCKER_REGISTRY_USER: ${{ github.actor }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_TOKEN }}
