name: Testing

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

defaults:
  run:
    working-directory: ./

jobs:
  app-testing:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@8aeb6ff8030dd539317f8e1769a044873b56ea71 # v1.268.0
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Install Dependencies
        run: bundle install

      - name: Run Tests
        run: bundle exec rake test

      - name: Generate coverage report
        uses: mridang/action-test-reporter@v1.7.0
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: 'build/coverage/coverage.xml'

      - name: Upload Results
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        if: always()
        with:
          name: test-results
          path: build/reports/**/*.xml

      - name: Generate Report
        if: ${{ always() && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false) }}
        uses: dorny/test-reporter@fe45e9537387dac839af0d33ba56eed8e24189e8 # v2.3.0
        with:
          name: Tests
          reporter: java-junit
          path: build/reports/**/*.xml
          token: ${{ secrets.GITHUB_TOKEN }}
