name: Testing

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
    secrets:
      BASE_URL:
        required: false
      AUTH_TOKEN:
        required: false
      JWT_KEY:
        required: false
      CLIENT_ID:
        required: false
      CLIENT_SECRET:
        required: false

defaults:
  run:
    working-directory: ./

jobs:
  app-testing:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Install Dependencies
        run: bundle install

      - name: Run Tests
        run: bundle exec rake
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

      - name: Upload Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: build/reports/**/*.xml

      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-coverage
          path: build/coverage/coverage.xml

      - name: Generate Report
        if: ${{ always() && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false) }}
        uses: dorny/test-reporter@v2.0.0
        with:
          name: Tests
          reporter: java-junit
          path: build/reports/**/*.xml
          token: ${{ secrets.GITHUB_TOKEN }}
