name: Testing

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

defaults:
  run:
    working-directory: ./

jobs:
  app-testing:
    runs-on: ubuntu-latest
    name: Run Tests

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          bundler-cache: true

      - name: Install Dependencies
        run: bundle install

      - name: Run Tests
        run: bundle exec rake test

      - name: Generate coverage report
        uses: mridang/action-test-reporter@v1.7.0
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: 'build/coverage/coverage.xml'

      - name: Upload Results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: test-results
          path: build/reports/**/*.xml

      - name: Generate Report
        if: ${{ always() && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false) }}
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3.0.0
        with:
          name: Tests
          reporter: java-junit
          path: build/reports/**/*.xml
          token: ${{ secrets.GITHUB_TOKEN }}
