# frozen_string_literal: true

# rubocop:disable all
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

module Zitadel::Client
  # Wraps an HTTP response with status code, body, and headers.
  class ApiHttpResponse
    attr_reader :status_code, :body, :headers

    def initialize(status_code:, body:, headers:)
      @status_code = status_code
      @body = body
      @headers = headers
    end
  end
end
