# frozen_string_literal: true

# rubocop:disable all
# Zitadel SDK
# The Zitadel SDK is a convenience wrapper around the Zitadel APIs to assist you in integrating with your Zitadel environment. This SDK enables you to handle resources, settings, and configurations within the Zitadel platform.
#
# The version of the OpenAPI document: 1.0.0
#
# Generated by: https://openapi-generator.tech

module Zitadel::Client
  # Unified entry point for all API services.
  #
  # Takes an {Auth::Authenticator} and optionally {TransportOptions},
  # then exposes each API group as a typed property. If the authenticator
  # includes {Auth::HttpAwareAuthenticator}, the shared {ApiClient} is
  # injected so that authentication HTTP calls (token exchange, discovery)
  # use the same transport configuration as regular API calls.
  #
  # @example Default transport
  #   client = Zitadel::Client::Client.new(authenticator)
  #
  # @example Custom transport (proxy, timeouts, etc.)
  #   transport = Zitadel::Client::TransportOptions.builder
  #     .proxy('http://proxy:3128')
  #     .timeout(5000)
  #     .build
  #   client = Zitadel::Client::Client.new(authenticator, transport)
  class Client
    # @return [Zitadel::Client::Api::ActionServiceApi]
    attr_reader :action_service

    # @return [Zitadel::Client::Api::ApplicationServiceApi]
    attr_reader :application_service

    # @return [Zitadel::Client::Api::AuthorizationServiceApi]
    attr_reader :authorization_service

    # @return [Zitadel::Client::Api::BetaActionServiceApi]
    attr_reader :beta_action_service

    # @return [Zitadel::Client::Api::BetaAppServiceApi]
    attr_reader :beta_app_service

    # @return [Zitadel::Client::Api::BetaAuthorizationServiceApi]
    attr_reader :beta_authorization_service

    # @return [Zitadel::Client::Api::BetaFeatureServiceApi]
    attr_reader :beta_feature_service

    # @return [Zitadel::Client::Api::BetaInstanceServiceApi]
    attr_reader :beta_instance_service

    # @return [Zitadel::Client::Api::BetaInternalPermissionServiceApi]
    attr_reader :beta_internal_permission_service

    # @return [Zitadel::Client::Api::BetaOIDCServiceApi]
    attr_reader :beta_oidc_service

    # @return [Zitadel::Client::Api::BetaOrganizationServiceApi]
    attr_reader :beta_organization_service

    # @return [Zitadel::Client::Api::BetaProjectServiceApi]
    attr_reader :beta_project_service

    # @return [Zitadel::Client::Api::BetaSessionServiceApi]
    attr_reader :beta_session_service

    # @return [Zitadel::Client::Api::BetaSettingsServiceApi]
    attr_reader :beta_settings_service

    # @return [Zitadel::Client::Api::BetaTelemetryServiceApi]
    attr_reader :beta_telemetry_service

    # @return [Zitadel::Client::Api::BetaUserServiceApi]
    attr_reader :beta_user_service

    # @return [Zitadel::Client::Api::BetaWebKeyServiceApi]
    attr_reader :beta_web_key_service

    # @return [Zitadel::Client::Api::FeatureServiceApi]
    attr_reader :feature_service

    # @return [Zitadel::Client::Api::IdentityProviderServiceApi]
    attr_reader :identity_provider_service

    # @return [Zitadel::Client::Api::InstanceServiceApi]
    attr_reader :instance_service

    # @return [Zitadel::Client::Api::InternalPermissionServiceApi]
    attr_reader :internal_permission_service

    # @return [Zitadel::Client::Api::OIDCServiceApi]
    attr_reader :oidc_service

    # @return [Zitadel::Client::Api::OrganizationServiceApi]
    attr_reader :organization_service

    # @return [Zitadel::Client::Api::ProjectServiceApi]
    attr_reader :project_service

    # @return [Zitadel::Client::Api::SAMLServiceApi]
    attr_reader :saml_service

    # @return [Zitadel::Client::Api::SessionServiceApi]
    attr_reader :session_service

    # @return [Zitadel::Client::Api::SettingsServiceApi]
    attr_reader :settings_service

    # @return [Zitadel::Client::Api::UserServiceApi]
    attr_reader :user_service

    # @return [Zitadel::Client::Api::WebKeyServiceApi]
    attr_reader :web_key_service

    # Creates a new client with the given authenticator and optional transport options.
    #
    # If the authenticator includes {Auth::HttpAwareAuthenticator}, the shared
    # {ApiClient} is injected so that token exchange and discovery requests
    # use the same proxy, TLS, and timeout settings.
    #
    # @param authenticator [Auth::Authenticator] Provides host URL and auth headers.
    # @param transport_options [TransportOptions, nil] HTTP transport configuration.
    def initialize(authenticator, transport_options = nil)
      transport_options ||= TransportOptions.builder.build
      api_client = DefaultApiClient.new(transport_options)
      authenticator.api_client = api_client if authenticator.is_a?(Auth::HttpAwareAuthenticator)

      config = Configuration.builder
        .base_url(authenticator.host)
        .build
      @action_service = Api::ActionServiceApi.new(api_client, config, authenticator)
      @application_service = Api::ApplicationServiceApi.new(api_client, config, authenticator)
      @authorization_service = Api::AuthorizationServiceApi.new(api_client, config, authenticator)
      @beta_action_service = Api::BetaActionServiceApi.new(api_client, config, authenticator)
      @beta_app_service = Api::BetaAppServiceApi.new(api_client, config, authenticator)
      @beta_authorization_service = Api::BetaAuthorizationServiceApi.new(api_client, config, authenticator)
      @beta_feature_service = Api::BetaFeatureServiceApi.new(api_client, config, authenticator)
      @beta_instance_service = Api::BetaInstanceServiceApi.new(api_client, config, authenticator)
      @beta_internal_permission_service = Api::BetaInternalPermissionServiceApi.new(api_client, config, authenticator)
      @beta_oidc_service = Api::BetaOIDCServiceApi.new(api_client, config, authenticator)
      @beta_organization_service = Api::BetaOrganizationServiceApi.new(api_client, config, authenticator)
      @beta_project_service = Api::BetaProjectServiceApi.new(api_client, config, authenticator)
      @beta_session_service = Api::BetaSessionServiceApi.new(api_client, config, authenticator)
      @beta_settings_service = Api::BetaSettingsServiceApi.new(api_client, config, authenticator)
      @beta_telemetry_service = Api::BetaTelemetryServiceApi.new(api_client, config, authenticator)
      @beta_user_service = Api::BetaUserServiceApi.new(api_client, config, authenticator)
      @beta_web_key_service = Api::BetaWebKeyServiceApi.new(api_client, config, authenticator)
      @feature_service = Api::FeatureServiceApi.new(api_client, config, authenticator)
      @identity_provider_service = Api::IdentityProviderServiceApi.new(api_client, config, authenticator)
      @instance_service = Api::InstanceServiceApi.new(api_client, config, authenticator)
      @internal_permission_service = Api::InternalPermissionServiceApi.new(api_client, config, authenticator)
      @oidc_service = Api::OIDCServiceApi.new(api_client, config, authenticator)
      @organization_service = Api::OrganizationServiceApi.new(api_client, config, authenticator)
      @project_service = Api::ProjectServiceApi.new(api_client, config, authenticator)
      @saml_service = Api::SAMLServiceApi.new(api_client, config, authenticator)
      @session_service = Api::SessionServiceApi.new(api_client, config, authenticator)
      @settings_service = Api::SettingsServiceApi.new(api_client, config, authenticator)
      @user_service = Api::UserServiceApi.new(api_client, config, authenticator)
      @web_key_service = Api::WebKeyServiceApi.new(api_client, config, authenticator)
    end

    # Creates a client authenticated with a static Bearer token.
    # @param host [String] API base URL.
    # @param access_token [String] Bearer token.
    # @param transport_options [TransportOptions, nil] Optional HTTP transport configuration.
    # @return [Client] Configured client instance.
    def self.with_token(host, access_token, transport_options = nil)
      new(Auth::BearerAuthenticator.new(host, access_token), transport_options)
    end
  end
end
